# GitHub Pages Configuration f端r Jekyll
title: "Buderus Systeme Team Cards"
description: "Digital Business Cards for Team Members"

# Wichtige Einstellungen f端r GitHub Pages
plugins:
  - jekyll-sitemap

# Include wichtige Dateien
include:
  - "*.json"
  - "*.js"
  - ".htaccess"

# Exclude bestimmte Dateien vom Build
exclude:
  - "README.md"
  - "deploy.sh"

# Collections f端r besseres Routing (optional)
collections:
  employees:
    output: false

# Sass Konfiguration
sass:
  sass_dir: _sass
  style: compressed

# Routing f端r GitHub Pages
kramdown:
  input: GFM
  hard_wrap: false

# Zeitzone
timezone: Europe/Berlin
